spring.application.name=financas-api

# configuraçao do banco de dados (supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.max-lifetime=24000
spring.datasource.hikari.connection-test-query=SELECT 1

#Configuraçao do JPA (Hibernate)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update